### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by sanbales** [JoelStansbury/PDFDigitizer#4]
With the `anaconda-project` PR, we should be able to more easily execute tests, but we need to write tests, or have notebooks that test things.

I know this is hard because there are a lot of interactions.

One thing to consider is that if we need fixture data, we may want to put those in a submodule so as to not pollute this repo with large files.

**Comment by JoelStansbury** [comment]
The tests actually weren't too bad. It even seems like a viable framework for programmatic usage
https://github.com/JoelStansbury/ipypdf/tree/main/tests
