### ISSUE TITLE
Consider Rename?

### ISSUE THREAD

**Issue by sanbales** [JoelStansbury/PDFDigitizer#5]
Wonder if there is a pithier name?

Possible suggestions:

* `ipypdf` to indicate it can play with the ipython/jupyter ecosystem of widgets
* `pdf2nlp` to indicate that it is a way to help interpret PDFs for natural language processing activities

**Comment by JoelStansbury** [comment]
Renamed to `ipypdf`, moved to a new repo so that the previously shared links don't break
